apiVersion: v1
kind: Service
metadata:
  name: votarg-backend
spec:
  type: LoadBalancer
  ports:
  - port: ${{ secrets.APP_PORT }}
    targetPort: ${{ secrets.APP_PORT }}
  selector:
    role: votarg-backend
